Tradução Cap 00 Introdução
rust-br/rust-book-pt-br pull request #101
Opened 2020-07-11 22:43 UTC by amargarido

Tradução do capítulo 00 **Introdução** (segunda edição do livro).

Endereça as Issues #25 , #75.

Endereça o pull request #76.

2020-07-11 22:53 UTC, leoyvens requested changes
Excelente! Pode corrigir os comentarios e tirar o ingles.

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +### Time de Desenvolvedores
TIme -> Times

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +um papel de _gatekeeper_ (guardião), recusando-se a compilar código com esses tipos de
Sem necessidade de manter o termo original 'gatekeeper'.

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +em conjunto) com o compilador, a equipe pode dedicar mais tempo à lógica do programa, em
Sem necessidade dos termos em parenteses, pode remover o '(simultaneidade)' e '(do mesmo lado; 
em conjunto)'.

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +  (preenchimento de código) e *inline error messages* (mensagens de erro em linha).
Tente tirar os termos em ingles desta frase.

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +ferramentas DevOps, dispositivos *embedded* (embarcados), análise e transcodificação de
Tirar o embedded e deixar so 'embarcados'.

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +áudio e vídeo, criptomoedas, bioinformática, motores de busca (search engines),
tirar o termo em parenteses.

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +ao código legado frágil (quebrável) em linguagens sem essas verificações, que os desenvolvedores
Tirar o termo em parenteses.

2020-07-11 22:53 UTC, leoyvens commented on second-edition/src/ch00-00-introduction.md
> +No Capítulo 16, abordaremos diferentes modelos de programação simultânea (concorrente) e como
Pode traduzir simplesmente como programacao concorrente, sem os parenteses.

2020-07-11 23:12 UTC, amargarido commented on second-edition/src/ch00-00-introduction.md
> +No Capítulo 16, abordaremos diferentes modelos de programação simultânea (concorrente) e como
Todos os ajustes acima realizados.

2020-07-11 23:41 UTC, leoyvens approved these changes
pode tirar o ingles

2020-07-12 12:54 UTC, merged

2020-09-25 16:18 UTC, adjoli commented
Prezados, esta seção ainda não está disponível.