Translate/summary
rust-br/rust-book-pt-br pull request #29
Opened 2017-08-13 03:05 UTC by amargarido

Tradução do Sumário.

Tive o cuidado de manter um termo traduzido (ou não) por todo o sumário.

IMHO o sumário é referência de tradução para demais partes do livro. 
Assim, seria bom, já formar um consenso desses termos que sugiro aqui.

Alguns termos não traduzi, pois acho que podem mais confundir que explicar: trait, lifetime, workspaces... entre outros. Penso que usar na forma original durante a tradução é melhor.

2017-08-13 04:31 UTC, marioidival commented on second-edition/src/SUMMARY.md
> +    - [Fatias](ch04-03-slices.md)
Eu acho interessante manter o Slice ou colocar entre parentes. Ja vi algumas traduções de linguagens como Python que ainda mantem o slice.

IMHO

2017-08-13 21:42 UTC, ericdouglas requested changes

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Referencias & Borrowing](ch04-02-references-and-borrowing.md)
Faltou acento em Referências.

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +- [Enum e Correspondência Entre Padrão (Match)](ch06-00-enums.md)
Aqui eu deixaria "Enums e Pattern Matching"

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Dados de Tipos Genéricos](ch10-01-syntax.md)
Não seria "Tipos de dados genéricos"? :thinking:

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +- [Projeto de E/S: Criando um Programa de Linha de Comando](ch12-00-an-io-project.md)
Acho que "I/O" fica melhor, e ai no capítulo a gente coloca "In/Out (Entrada/Saída)" em algum momento.

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Refatoração para Melhorar a Modularidade e o Tratamento de Erros](ch12-03-improving-error-handling-and-modularity.md)
Usaria "Refatorando" aqui ao invés de "Refatoração"

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Tarefas](ch16-01-threads.md)
Deixaria "threads" mesmo, sem traduzir

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +- [Correspondência de Padrões e Estrutura de Valores](ch18-00-patterns.md)
Essa frase aqui tá difícil de traduzir haha

Acho que colocaria assim: "Padrões correspondentes à estrutura dos valores"

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Refutabilidade: Se um Padrão Falha na Correspondência](ch18-02-refutability.md)
"Refutabilidade: Se um padrão falha no _match_"

Acho ruim traduzir *match* por estar muito ligado ao "pattern matching", que creio deve ser uma expressão que devemos deixar em inglês mesmo.

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +- [Projeto Final: Criando um Servidor Web Multi-Tarefa](ch20-00-final-project-a-web-server.md)
Projeto Final: Criando um Servidor Web Multithreaded

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Servidor Web de Única Tarefa](ch20-01-single-threaded.md)
Servidor Web de Uma thread

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Quão Lentos os `request` Afetam a Taxa de Transferência](ch20-02-slow-requests.md)
Como requisições lentas afetam a taxa de transferência

2017-08-13 21:42 UTC, ericdouglas commented on second-edition/src/SUMMARY.md
> +    - [Criando um Pool de Tarefas e as Guardando](ch20-04-storing-threads.md)
Criando um Pool de Threads e as Guardando

2017-08-13 22:13 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Referencias & Borrowing](ch04-02-references-and-borrowing.md)
Ajustando.

2017-08-13 22:14 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Dados de Tipos Genéricos](ch10-01-syntax.md)
Ajustando.

2017-08-13 22:15 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +- [Enum e Correspondência Entre Padrão (Match)](ch06-00-enums.md)
Ajustando.

2017-08-13 22:16 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Fatias](ch04-03-slices.md)
Ajustando.

2017-08-13 22:17 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +- [Projeto de E/S: Criando um Programa de Linha de Comando](ch12-00-an-io-project.md)
Ajustando.

2017-08-13 22:18 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Refatoração para Melhorar a Modularidade e o Tratamento de Erros](ch12-03-improving-error-handling-and-modularity.md)
Ajustando.

2017-08-13 22:18 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Tarefas](ch16-01-threads.md)
Ajustando.

2017-08-13 22:19 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +- [Correspondência de Padrões e Estrutura de Valores](ch18-00-patterns.md)
Ajustando.

2017-08-13 22:20 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Refutabilidade: Se um Padrão Falha na Correspondência](ch18-02-refutability.md)
Ajustando.

2017-08-13 22:21 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +- [Projeto Final: Criando um Servidor Web Multi-Tarefa](ch20-00-final-project-a-web-server.md)
Ajustando.

2017-08-13 22:23 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Servidor Web de Única Tarefa](ch20-01-single-threaded.md)
Ok, 
daí ajusto a outra linha para:

Projetando a Interface de Threads.

2017-08-13 22:25 UTC, amargarido commented on second-edition/src/SUMMARY.md
> +    - [Criando um Pool de Tarefas e as Guardando](ch20-04-storing-threads.md)
Ajustando.

2017-08-13 22:56 UTC, amargarido commented
Dúvida... fiz novo commit e pedi um pull. Vcs estão vendo aí ?  Temo que fiz algo errado.

2017-08-13 23:04 UTC, ericdouglas commented
@amargarido aqui está tudo ok, dá para fazer o merge sem conflitos.

2017-08-13 23:05 UTC, ericdouglas approved these changes

2017-08-13 23:07 UTC, ericdouglas commented
@amargarido está ótimo :smile: :tada: Muito obrigado pela ajuda!

2017-08-14 12:35 UTC, marioidival approved these changes
LGTM

2017-08-14 14:42 UTC, merged

2017-08-15 00:04 UTC, ericdouglas commented
@marioidival @amargarido agora que vi, esse arquivo tinha que ser traduzido [aqui](https://github.com/rust-br/rust-book-pt-br/tree/master/src) certo?!

Os conteúdos em `/second-edition/src` devem ficar sem mexer.