Adiciona tradução do capítulo 01
rust-br/rust-book-pt-br pull request #31
Opened 2017-08-22 13:25 UTC by andrealmar

Adicionando tradução do capítulo 01, seções Instalação e Hello World!

2017-10-09 00:31 UTC, leoyvens requested changes

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +de cada comando. Você vai notar em muitos tutorias disponíveis por aí que eles seguem
em muitos tutorias disponíveis por aí que eles seguem -> que muitos tutoriais disponíveis por aí seguem

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +Se você está em um ambiente Linux ou Mac, tudo o que você precisa é abrir seu Terminal e digitar o seguinte comando:
Terminal -> terminal

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +Este comando vai baixar um script e iniciar a instalação. Talvez um prompt vai aparecer na sua tela requerendo o seu password. Se tudo ocorrer bem, a mensagem abaixo vai aparecer:
Talvez um prompt vai aparecer na sua tela requerendo o seu password ->
Talvez sua senha seja requerida

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +Em um ambiente Windows, vá até o endereço [https://rustup.rs](https://rustup.rs/)<!-- ignore --> e
vá até o endereço -> vá para

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +O restante dos comandos específicos para um ambiente Windows neste livro, partem da premissa que você está
sem vírgula

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +installation page](https://www.rust-lang.org/install.html) para outras opções de instalação.
traduzir link, linkar para https://www.rust-lang.org/pt-BR/install.html

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +Do seu shell, execute script de atualização:
script -> o script

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +Se nao aparecer a mensagem acima e você está em um ambiente Windows, verifique nas suas variáveis de ambiente se Rust aparece no seu`%PATH%`.
nao -> não
seu`%PATH%` -> seu `%PATH%`

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +O instalador também inclui uma cópia da documentação, para que você possa acessá-la offline. Execute o comando `rustup doc` para abrir a documentação local no seu browser.
browser -> navegador

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-01-installation.md
> +Toda vez que se reparar com um tipo ou função fornecido pela biblioteca padrão e você não tiver certeza do que ela faz, use a documentação para descobrir mais a respeito!
se reparar -> se deparar
para descobrir mais a respeito! -> para descobrir!

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-02-hello-world.md
> +“Hello, world!” na tela, e é exatamente isso que iremos fazer nesta seção.
Será que vale a pena traduzir "Hello, world!" para "Olá, mundo!"? É legal que mostra o suporte para Unicode.

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-02-hello-world.md
> +### Criando um diretório de projeto
diretório de projeto -> Diretório de Projeto

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-02-hello-world.md
> +Primeiramente, crie um diretório para armazenar o seu código Rust. Rust não se importa aonde você vai armazenar o seu código, mas enquanto lê este livro, nós sugerimos criar um diretório chamado *pro
enquanto lê este livro -> neste livro
projects -> projetos

2017-10-09 00:31 UTC, leoyvens commented on second-edition/src/ch01-02-hello-world.md
> +terminam com a extensão *.rs* . Se você for nomear o seu arquivo com mais de um nome, use
um nome -> uma palavra

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Isso faz de você um programador Rust!
Faltou o "Bem vindo!"

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +### Anatomia de um Programa escrito em Rust
Programa ecrito em Rust -> Programa Rust

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Se existissem parâmetros, eles estariam dentro dos parênteses, `(` and `)`.
and -> e

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Também vale notar que o corpo da função está envolvida por duas chaves, `{` and `}`. Rust
envolvida -> envolvido
and -> e

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Dentro da função `main` :
sem espaço antes do :

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +na tela. Existem alguns detalhes a se notar aqui. O primeiro é que estilo de identação de Rust
estilo -> o estilo
identação -> indentação

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +### Compilação e Execução são Diferentes Etapas
são -> São

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Antes de executar qualquer programa em Rust, voce deve compilá-lo. Você deve usar o compilador Rust utilizando o comando `rustc` junto com o nome do seu código fonte conforme o exemplo abaixo:
deve -> pode
código fonte -> arquivo fonte

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Temos aqui dois arquivos: o código fonte, que termina com a extensão *.rs*, e o arquivo  executável (*main.exe* no Windows, *main* em qualquer outro Sistema Operacional). O que nos resta fazer é exec
Sistema Operacional -> sistema operacional
sem espaço antes do :

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Se você programa utilizando uma linguagem dinâmica como Ruby, Python, ou JavaScript, você provavelmente não está acostumado compilar para só depois executar um programa. Rust é uma linguagem *ahead-o
acostumado compilar -> acostumado a compilar
para só depois -> para depois

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Em se tratando de programas simples, compilar utilizando `rustc` servirá na maioria dos casos, mas conforme o seu projeto cresce, você com certeza vai querer gerenciar todas as opções possíveis para
o outros -> outros

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Vamos criar um novo projeto usando Cargo e ver o que o diferencia do nosso primeiro projeto `hello_world`. Volte so seu diretório de projetos (ou aonde quer que você colocou o seu código):
so seu -> ao seu

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Se listarmos os arquivos no nosso diretório *hello_cargo*, podemos ver que Cargo gerou dois arquivos e um diretório para nós: um arquivo *Cargo.toml* e um diretório *src* com um arquivo *main.rs* den
diferente sistema -> sistema diferente

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +A primeira linha, `[package]`, é um cabeçalho de seção que indica que o que se segue, está configurando um pacote. Ao passo que adicionamos mais informações neste arquivo, vamos adicionando outras se
sem vírgula

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +A última linha, `[dependencies]`, é o começo da seção em que você deve listar quaisquer *crates* (que é como chamamos pacotes de código Rust) que seu projeto irá depender. Assim o Cargo saberá que de
que seu -> das quais

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +O Cargo gerou um “Hello World!” para você, igual o que a gente escreveu anteriormente!  As diferenças entre o projeto que geramos e o projeto que o Cargo gerou para nósaté agora foram:
espaço duplo
nósaté -> nós até

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Cargo usa o arquivo *Cargo.lock* para rastrear as dependências na sua aplicação.
na -> da

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +### Do Build à Release
Melhor "Build em Formato Release

2017-10-09 00:31 UTC, leodasvacas commented on second-edition/src/ch01-02-hello-world.md
> +Quando o seu projeto está finalmente pronto para release, você pode usar o comando `cargo build --release` para compilar o seu projeto com otimizações. Isso vai criar um arquivo executável no diretór
para release -> para ser lançado

2017-10-09 00:32 UTC, leodasvacas commented
Valeu pela tradução André! Fiz uma revisão com pequenos comentários, no geral tá show.

2017-10-20 13:16 UTC, marioidival commented
@andrealmar o/

2017-10-26 19:14 UTC, leodasvacas commented
@andrealmar desistiu? Nesse caso alguém vai precisar pegar o branch dele, fazer as correções e remover o texto em inglês para termos um capítulo 1.

2017-10-26 19:33 UTC, andrealmar commented
@leodasvacas podem prosseguir. Não poderei continuar com a tradução do livro.

2017-12-20 20:54 UTC, Milack27 commented
Tradução já incorporada ao repositório através do pull request #40.

2017-12-20 20:54 UTC, closed without merging