Chapter5 tradução
rust-br/rust-book-pt-br pull request #33
Opened 2017-10-29 01:11 UTC by jotaerreah

Boa noite,

Capitulo 5 traduzido. Agradeço revisão e opiniões, s.f.f.

2017-10-29 13:28 UTC, iha reviewed
Não terminei a review, vou continuar depois.

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-00-structs.md
> +comparar e contrastar tuples com structs, demonstrar como usar structs e
Eu acho que "comparar e diferenciar tuplas com structs" é melhor.

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +﻿## Defining and Instantiating Structs
O título em inglês pode ser retirado

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +Structs são semelhantes às tuples, que foram discutidas no Capítulo 3. Como
Acho que todas ocorrências de tuples podem ser trocadas por tuplas.

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +tuples, as peças de uma struct podem ser de tipos diferentes. Ao contrário das
Acho que fica melhor "os elementos de uma struct podem ser de tipos diferentes."

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +saber a ordem dos dados para especificar ou aceder aos valores de uma instância.
Acessar ao invés de aceder.

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +Para definir um struct, digite a chave 'struct' e o nome todo o struct. O nome
Acho que pode omitir "a chave", ou usar "a palavra-chave".

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +das chavetas, vamos definir os nomes e tipos dos dados, o que chamamos de
"chaves" no lugar de "chavetas"

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +*campos*. Por exemplo, lista 5-1 mostra uma struct para armazenar informações
Será que não é melhor substituir "Listing" por "Código" ou "Figura" ?

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +especificando valores concretos para cada um dos campos. Estamos a criar uma
Acho que "concretos" pode ser omitido.

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +especificando valores concretos para cada um dos campos. Estamos a criar uma
"Nós criamos uma" ao invés de "Estamos a criar uma"

2017-10-29 13:28 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +instância, indicando o nome da struct e depois entre chavetas, adicionamos
"e depois entre chaves, adicionamos os pares `key: value`"
Aqui nós temos um problema, pois '{' é uma chave e key em português é chave também, não seria melhor manter `key: value` em inglês?

2017-10-29 15:07 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +valores são os dados que deseja armazenar nesses campos. Nós não temos para
De: "Nós não temos para especificar os campos na mesma ordem em que os temos declarado na struct"
para: "Nós não temos que atribuir os elementos na mesma ordem que eles foram declarados na definição da struct"

2017-10-29 15:13 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +outras palavras, a definição da struct é como um modelo geral para o tipo, e as
De: "a definição da struct é como um modelo geral para o tipo"
Para: "a definição da struct é como um modelo genérico para o tipo"

Acho poderia manter template ao invés de traduzir pra modelo.

2017-10-29 15:18 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +instância, indicando o nome da struct e depois entre chavetas, adicionamos
Que tal `campo:valor`?

2017-10-29 15:20 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +outras palavras, a definição da struct é como um modelo geral para o tipo, e as
Genérico não é bom porque confunde com tipos genéricos que é outra coisa, acho que está bem como está.

2017-10-29 15:20 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +instância, indicando o nome da struct e depois entre chavetas, adicionamos
sim, `campo:valor` fica melhor.

2017-10-29 15:22 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +﻿## Defining and Instantiating Structs
Deixamos o original em inglês para facilitar a revisão até completar a tradução. Mas seria bom colocar os títulos em maíusculo assim como estão em inglês.

2017-10-29 15:23 UTC, iha commented on second-edition/src/ch05-01-defining-structs.md
> +outras palavras, a definição da struct é como um modelo geral para o tipo, e as
Pode ser, só vi que tem isso porque você comentou e acabei olhando na aba do livro :) Não cheguei ainda no cap 10.

2017-10-29 15:58 UTC, jotaerreah commented on second-edition/src/ch05-00-structs.md
> +comparar e contrastar tuples com structs, demonstrar como usar structs e
Não vi os capitulos anteriores em termos de tradução. Como tuples é uma 'definição de código', como struct, achei melhor não traduzir.
O contrastar saiu da tradução automática e quando li não estranhei. Concordo com a alteração, parece mais natural.

2017-10-29 16:01 UTC, jotaerreah commented on second-edition/src/ch05-01-defining-structs.md
> +saber a ordem dos dados para especificar ou aceder aos valores de uma instância.
Aqui a diferença entre pt e br. Para mim, pt, aceder é mais correto.Acho que meto as duas, com uma entre parênteses.

2017-10-29 16:08 UTC, leodasvacas commented on second-edition/src/ch05-00-structs.md
> +comparar e contrastar tuples com structs, demonstrar como usar structs e
Tuplas é usual, pode traduzir tuples como tuplas.

2017-10-29 16:14 UTC, jotaerreah commented
Trocar chavetas por chaves, como fica depois este texto?
Para mim, PT, chavetas é igual a {}. 

Estamos a criar uma instância, indicando o nome da struct e depois entre chavetas,
adicionamos elementos contendo pares ‘chave:valor’ onde as chaves são os nomes dos 
campos e os valores são os dados que deseja armazenar nesses campos.

2017-11-04 16:10 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +tuples, as peças de uma struct podem ser de tipos diferentes. Ao contrário das
_Elementos_ geralmente se refere a uma sequência, acho melhor usar _campos_.

2017-11-04 16:11 UTC, leodasvacas commented
Se em PT se usa chavetas, então é válido deixar como chavetas.

2017-11-04 18:31 UTC, marioidival approved these changes
SGTM

2017-11-07 11:39 UTC, leodasvacas commented
@marioidival Se está aprovado agora é só tirar o inglês, certo?

2017-11-07 14:56 UTC, marioidival commented
@leodasvacas Sim!

2017-11-07 15:10 UTC, jotaerreah commented
Vou retirar o inglês então.
Mais logo replico as alterações.

2017-11-07 15:27 UTC, jotaerreah commented
Revendo mais uma vez, apanhei esta possivel correcção.
### Tuple Structs sem Campos Nomeados para Criar Tipos Diferentes
que acham?
### Structs Tuplas sem Campos Nomeados para Criar Tipos Diferentes

2017-11-07 17:53 UTC, leodasvacas commented
Sugestão: Struct-tupla.

2017-11-24 12:19 UTC, leoyvens requested changes
A tradução está excelente, obrigado @jotaerreah! Em uma revisão final peguei algumas pequenas correções.

2017-11-24 12:19 UTC, leoyvens commented on second-edition/src/ch05-00-structs.md
> +comparar e diferenciar tuples com structs, demonstrar como usar structs e
tuples -> tuplas

2017-11-24 12:19 UTC, leoyvens commented on second-edition/src/ch05-01-defining-structs.md
> +das  tuplas, nomeie cada dado de modo que seja claro o que cada um significa.
espaço duplo em "das  tuplas"

2017-11-24 12:19 UTC, leoyvens commented on second-edition/src/ch05-01-defining-structs.md
> +chaves contendo pares `campo:valor` onde as chaves são os nomes dos campos
"adicionamos chaves contendo pares" -> ""adicionamos pares"

2017-11-24 12:19 UTC, leoyvens commented on second-edition/src/ch05-01-defining-structs.md
> +<span class="caption">Lista 5-2: Criar uma instancia da struct `User`</span>
instância

2017-11-24 12:19 UTC, leoyvens commented on second-edition/src/ch05-01-defining-structs.md
> +### Abreviatura do Init dos Campos quando as Variáveis têm o mesmo Nome dos Campos
do Init -> da inicialização

2017-11-24 12:19 UTC, leoyvens commented on second-edition/src/ch05-01-defining-structs.md
> +funções que criam novas instâncias de structs mais concisos. Em primeiro lugar,
campo *init shorthand* (iniciar curto) -> *field init shorthand* (inicialização abreviada do campo)

mais concisos -> sejam mais concisas

2017-11-24 12:19 UTC, leoyvens commented on second-edition/src/ch05-01-defining-structs.md
> +A sintaxe do campo init pode fazer casos como esse mais curtos para escrever,
sintaxe do campo init -> sintaxe abreviada

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +configurado deve ter o mesmo valor que os campos na determinada instância.
configurado deve -> configurados devem

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +nome da struct, que são seguidos pelos tipos na tuple. Por exemplo, aqui estão
tuple -> tupla

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +as definições e usos da tuple structs chamado `Color` e `Point`:
da tuple struct -> da struct-tupla

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +são de diferentes instâncias tuple structs. Cada struct que definimos é o seu
são de diferentes instâncias tuple structs -> são instâncias de diferentes structs-tuplas.

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +contrário, as tuple struct comportam-se como instâncias de tuplas, que
Caso contrário -> No geral
tuple struct -> structs-tuplas

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +quaisquer dados que você deseja armazenar no tipo em si. Traits será discutido
Traits será -> Traits serão

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +### Reprogramação com Structs: Adicionando Mais Significado
No Brasil traduzimos refactoring como refatoração. Como é em Portugal?

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +Usamos structs para dar significado aos dados usando rotulos. Podemos
rotulos -> rótulos

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +os seus campos. Lista 5-11 usa a macro 'Println!' como temos usado nos
Println -> println

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +A macro 'Println!' pode fazer muitos tipos de formatação, e por padrão,
Println -> println

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +Structs, a forma como `Println!` deve formatar a saída é menos clara, pois
Println -> println

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +Avisa que `Rectangle` não pode ser formatado com o formato por defeito;
por defeito -> padrão

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +Rust *não* inclui funcionalidades para imprimir informações de depuração,
*não* inclui -> *inclui*

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +temos de inseri-la explicitamente para tornar essa funcionalidade disponível
temos -> mas temos

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-03-method-syntax.md
> +## Sintaxe do Metodo
Metodo -> Método

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-03-method-syntax.md
> +### Definindo Metodos
Metodo -> Método

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-03-method-syntax.md
> +podemos usar o *método sintaxe* (method sintax) para chamar o método `área`
*método sintaxe* (method sintax) -> *sintaxe de método* (method syntax)

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-03-method-syntax.md
> +na nossa instância `Rectangle`. A sintaxe método vem em seguida a uma instância:
sintaxe método -> sintaxe de método

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-03-method-syntax.md
> +### Metodos com Mais Parametros
Parametros -> Parâmetros

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-03-method-syntax.md
> +respectivamente. Vamos adicionar o novo metodo `can_hold` ao bloco `impl`
metodo -> método

2017-11-24 12:19 UTC, leodasvacas commented on second-edition/src/ch05-03-method-syntax.md
>  specify the same value twice:
Faltou remover este parágrafo em inglês.

2017-11-28 12:17 UTC, jotaerreah commented on second-edition/src/ch05-01-defining-structs.md
> +quaisquer dados que você deseja armazenar no tipo em si. Traits será discutido
Em relação a traits, houve uma conversa sobre a tradução, se houve final eu perdi.
Como fica, traduz-se ou não? Traits, caracteristicas, funcionalidades, ....?

2017-11-28 12:18 UTC, jotaerreah commented on second-edition/src/ch05-02-example-structs.md
> +### Reprogramação com Structs: Adicionando Mais Significado
Aqui não tem tradução direta. Podemos dizer que refatoração serve. No caso vi qual o obejtivo do titulo, por isso reprogramação.

2017-11-28 12:19 UTC, jotaerreah commented on second-edition/src/ch05-02-example-structs.md
> +os seus campos. Lista 5-11 usa a macro 'Println!' como temos usado nos
Esta foi o vscode.

2017-11-28 12:22 UTC, jotaerreah commented on second-edition/src/ch05-02-example-structs.md
> +Rust *não* inclui funcionalidades para imprimir informações de depuração,
Esta não percebi como aparece o não... sabotagem!!!!

2017-11-28 12:47 UTC, leodasvacas commented
@jotaerreah Ótimo, acho que faltaram só três correções da revisão.

2017-11-28 12:48 UTC, leodasvacas commented on second-edition/src/ch05-01-defining-structs.md
> +quaisquer dados que você deseja armazenar no tipo em si. Traits será discutido
É uma questão em aberto, não precisamos decidir neste momento.

2017-11-28 15:37 UTC, jotaerreah commented on second-edition/src/ch05-02-example-structs.md
> +### Reprogramação com Structs: Adicionando Mais Significado
Deixa-me corrigir.
Se você trabalha com um programa ERP, refatoração é refazer as faturas emitidas.
Verdade que isto é para programadores, mas e se um programador estiver a fazer um programa de faturação...Como vocês dizem pelo Brasil, neste caso? Refatoração é igual?

2017-11-28 15:37 UTC, jotaerreah commented on second-edition/src/ch05-02-example-structs.md
> +### Reprogramação com Structs: Adicionando Mais Significado
Aqui refactoring é mais refabricação.

2017-11-28 15:39 UTC, jotaerreah commented
Já que estamos nisto, sendo o meu primeiro nome José, estou mais habituado a zé.Esta do jotaerreah é mais para dar um nick.

2017-11-28 15:48 UTC, leodasvacas commented on second-edition/src/ch05-02-example-structs.md
> +### Reprogramação com Structs: Adicionando Mais Significado
Se parece confuso então mantemos Reprogramação.

2017-11-28 18:59 UTC, merged

2017-11-28 19:00 UTC, leodasvacas commented
Muito obrigado Zé pelo trabalho e persistência! Nosso primeiro capítulo traduzido 🎉

2018-02-23 21:43 UTC, hsribei commented
Cheguei aqui atrás de uma tradução para "tuple struct" =)

Quanto a "struct-tupla", acho esquisito misturar inglês e português no mesmo termo, e o "t-t" me parece meio cacofônico, mas se formos padronizar assim, o plural de substantivo-substantivo flexiona apenas o primeiro termo, então ficaria "structs-tupla" (também é possível flexionar os dois, "structs-tuplas", mas não só o último, "struct-tuplas").

Uma alternativa é traduzir no primeiro uso e em seguida usar "tuple struct" mesmo. Eu acho mais simples, até porque foge da complexidade a mais do plural descrita acima. Estou seguindo esta forma no Capítulo 15, mas se for decidido a primeira, substituo sem problema, claro.