Translate/chapter 08
rust-br/rust-book-pt-br pull request #34
Opened 2017-11-20 23:01 UTC by amargarido

Tradução do Cap 08.

Trechos de código com comentários, todo o trecho foi copiado e o comentário traduzido.

2017-11-24 12:29 UTC, afonsolage commented on second-edition/src/ch08-00-common-collections.md
> +# Coleções comuns
Não sei se foi decisão de estilo, mas sugiro colocar "Comuns" (em capital) para seguir o padrão das outras sessões.

2017-11-24 12:33 UTC, afonsolage commented on second-edition/src/ch08-00-common-collections.md
> +* Um *hash map* permite associar um valor a uma chave em particular. É uma
"permite associar um valor **à** uma chave em particular"

Nesse caso, 'associar' refere-se à uma palavra feminina (chave), então precisa ter crase.

2017-11-24 12:35 UTC, afonsolage commented on second-edition/src/ch08-00-common-collections.md
> +maps, bem como fazer cada um especial.
"bem como fazer cada um especial"

Nesse caso, acredito que a tradução mais adequada, seja algo como:
"bem como o que os tornam especial".

2017-11-24 12:40 UTC, afonsolage commented on second-edition/src/ch08-01-vectors.md
> +padrão code conter qualquer tipo, e quando um `Vec` específico possui um tipo específico, o
"code" -> "pode"

2017-11-24 12:43 UTC, afonsolage commented on second-edition/src/ch08-01-vectors.md
> +altere seu valor, precisamos fazê-lo mutable com a palavra-chave `mut`. Os
"altere" -> "alterar"

"[...] precisamos fazê-lo mutable com a palavra-chave [...]"
Acredito que seja mais didático chamar de mutável mesmo, pois nesse caso está havendo referência à propriedade mutável de uma variável, e não à um nome próprio ou palavra-chave.

2017-11-24 12:48 UTC, afonsolage commented on second-edition/src/ch08-01-vectors.md
> +Quando o vetor é descartado, todos os seus conteúdos também serão descartados, o que significa
"todos os seus conteúdos também serão descartados"

Acredito que uma tradução mais seria: "todo o seu conteúdo também será descartado".

2017-11-24 12:51 UTC, afonsolage commented on second-edition/src/ch08-01-vectors.md
> +ler o seu conteúdo é um bom passo seguinte. Existem duas maneiras de fazer referência a
"[...] saber como ler o seu conteúdo é um bom passo seguinte."
Nesse caso, acredito que possamos sair da tradução mais literal e mudar um pouco a frase, mas mantendo a coerência do sentido original:
"[...] o próximo passo é saber como ler o seu conteúdo."

2017-11-24 13:05 UTC, leodasvacas commented on second-edition/src/ch08-00-common-collections.md
> +* Um *hash map* permite associar um valor a uma chave em particular. É uma
Na verdade não se usa crase antes de artigo indefinido, então está correto como escrito.

2017-11-28 08:03 UTC, amargarido commented on second-edition/src/ch08-00-common-collections.md
> +# Coleções comuns
Sim, faltou o estilo aqui. Arrumando.

2017-11-28 08:05 UTC, amargarido commented on second-edition/src/ch08-00-common-collections.md
> +maps, bem como fazer cada um especial.
Ajustado.

2017-11-28 08:06 UTC, amargarido commented on second-edition/src/ch08-01-vectors.md
> +padrão code conter qualquer tipo, e quando um `Vec` específico possui um tipo específico, o
Ajustado.

2017-11-28 08:10 UTC, amargarido commented on second-edition/src/ch08-01-vectors.md
> +altere seu valor, precisamos fazê-lo mutable com a palavra-chave `mut`. Os
Ok, alterar. Ok, mutável.

2017-11-28 08:11 UTC, amargarido commented on second-edition/src/ch08-01-vectors.md
> +Quando o vetor é descartado, todos os seus conteúdos também serão descartados, o que significa
Ajustado.

2017-11-28 08:13 UTC, amargarido commented on second-edition/src/ch08-01-vectors.md
> +ler o seu conteúdo é um bom passo seguinte. Existem duas maneiras de fazer referência a
Ajustado.

2017-11-28 11:44 UTC, leoyvens requested changes
Muito boa a tradução, deixei algumas correções.

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-00-common-collections.md
> +e custo, e escolher o apropriado para cada tipo de situação em que se encontra é uma
possui capacidades diferentes e custo, e escolher o apropriado ->
possui diferentes capacidades e custos, e escolher a apropiada

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-00-common-collections.md
> +  implementação particular da estrutura de dados mais generalizada chamada de *map*.
generalizada -> geral

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-00-common-collections.md
> +maps, bem como o que os tornam especial.
especial -> especiais

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +### Descartando um Vetor descarta seus Elementos
Descartando -> Descartar
descarta -> Descarta

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +Como qualquer outro `struct`, um vetor será liberado quando ele estiver fora do escopo:
estiver fora do escopo -> sair do escopo

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +passo é saber ler o seu conteúdo é um bom passo seguinte. Existem duas maneiras de fazer referência a
remover "o próximo passo é"

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +valor armazenado em um vetor. Nos exemplos, anotamos os tipos de
valor armazenado -> valores armazenados

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +passado como um argumento, o que nos dá uma `Opção <& T>`.
Opção <& T> -> Option<&T>

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +não tem um elemento para ele. Por exemplo, o que um programa deve fazer se tiver
que o vetor não tem um elemento para ele -> para o qual o vetor não tem um elemento correspondente

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +Quando você executa isso, você encontrará que com o primeiro método `[]`, Rust irá
executa -> executar
encontrará -> verá

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +elemento, passado o fim do vetor, para ser um erro fatal que, deve travar o
travar -> finalizar
sem vírgula após o "que"

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +retorna `None` sem entrar em pânico. Você usaria isso se acessasse um elemento
acessasse -> acessar

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +as regras de propriedade e empréstimo abrangidas no Capítulo 4 para garantir essa referência e
garantir -> garantir que

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-01-vectors.md
> +de uso para a necessidade de armazenar uma lista de coisas de diferentes tipos. Felizmente, o
remover "o"

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +em profundidade agora. As strings são uma área que os novos Rustaceans geralmente tem maior
Rustaceans -> Rustáceos

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +certificando-se de expor possíveis erros, as strings são estruturas de dados mais complicadas
para certificando-se -> de certificar-se

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +combinar de tal forma que parecem difícil quando se vem de outras linguagens.
combinar -> combina,

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +falar sobre as operações em `String` que cada tipo de coleção tem, como
cada -> todo

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +da própria linguagem: `str`, a fatia de string, que geralmente é vista na forma de emprestado
de emprestado -> emprestada

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +, `&str`. Nós falamos como *fatias de strings* no Capítulo 4: estas são uma
como -> sobre

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +referência a alguns dados de string codificados UTF-8 armazenados em outro lugar. Literais de strings,
codificados -> codificados em

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +codificado no núleo da linguagem, e é extensível, mutável, `owned`, tipo string
núleo -> núcleo
e é -> e é um

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +codificado UTF-8. Quando Rustaceans falam sobre "strings" em Rust, geralmente significam
Rustaceans -> Rustáceos
significam -> significa

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +Muitas vezes, teremos alguns dados iniciais que gostaríamos de já iniciar a string.
iniciar a -> colocar na

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +que implementa a trait `Display`, que as string literais fazem:
que as string literais fazem -> como as string literais

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +`s` será ”jogo-da-velha” neste momento. Com todos os `+` e `"`
jogo-da-velha -> tic-tac-toe

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +caracteres, fica difícil ver o que está acontecendo. Para strings mais complicadas
remover "caracteres"

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +, podemos usar o `format!` macro:
`format!` macro -> macro `format!`

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +Este código também definirá `s` para ”jogo-da-velha”. A macro `format!` funciona
jogo-da-velha -> tic-tac-toe

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +#### Bytes e Valores Escalares e Grafema Clusters! Oh nossa!
Grafema Clusters -> Clusters de Grafemas
Oh nossa -> nossa

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +Se olharmos para a palavra Hindi “नमस्ते” escrita no script Devanagari, é
no script -> na escrita

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-02-strings.md
> +### As cordas não são tão simples
cordas -> strings
Colocar em maiúsculo

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-03-hash-maps.md
> +a lógica por nós mesmos e, além disso, trabalha-se de forma maislimpa com o borrow checker.
maislimpa -> mais limpa

2017-11-28 11:44 UTC, leodasvacas commented on second-edition/src/ch08-03-hash-maps.md
> +na verdade retorna uma referência mutável (`&mutV`) para o valor desta
&mutV -> & mutV

2017-11-28 19:12 UTC, leodasvacas commented
Obrigado pelas correções! Agora falta só remover o texto original em inglês.

2017-11-28 19:12 UTC, leoyvens approved these changes

2017-11-28 20:55 UTC, merged

2017-11-28 20:55 UTC, leodasvacas commented
Feito, mandou bem 💯