Traduz o capítulo 4
rust-br/rust-book-pt-br pull request #50
Opened 2018-02-17 23:03 UTC by Milack27

2018-02-20 11:03 UTC, leoyvens requested changes
Excelente tradução, português impecável, parabéns! Gostei da tradução de ownership como posse, podemos adotar como padrão. Parece que tem uns conflitos de merge que você pode resolver pegando a sua versão.

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-00-understanding-ownership.md
> +_Ownership_ (posse) é a característica mais peculiar do Rust, que o permite ter
"peculiar" pode ter conotação negativa, acho melhor "única".

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +> ### A _Stack_ e a _Heap_
Acho que podemos preferir "pilha" a "stack" em toda essa caixa, é um termo bem estabelecido.

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +> tão bem! Em inglês, diz-se *pushing onto the stack* quando se refere a inserir
" Em inglês, diz-se *pushing onto the stack*" -> "Dizemos fazer *push na pilha*"

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +> dados, e *popping off the stack* quando se refere a remover dados.
e fazer *pop na pilha*

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +> de *allocating on the heap*, e às vezes se abrevia esta frase como apenas
"Em inglês, este processo é chamado de *allocating on the heap*" ->
"Este processo se chama "alocar no heap*"

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +> _"allocating"_ (alocação). Colocar valores na stack não é considerado uma
_"allocating"_ (alocação) -> alocação

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +Mas então, qual é a diferença, aqui? Por que `String` pode ser alterada enquanto
"qual é a diferença, aqui?" -> "qual é a diferença aqui?"

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +1. A mempória deve ser solicitada ao sistema operacional em tempo de execução.
mempória -> memória

2018-02-20 11:03 UTC, leoyvens commented on src/ch04-01-what-is-ownership.md
> +If you’ve heard the terms “shallow copy” and “deep copy” while working with
trocar “shallow copy” por "cópia rasa" e "deep copy" por "cópia profunda", acho que é razoável traduzir.

2018-02-20 11:03 UTC, leodasvacas commented on src/ch04-01-what-is-ownership.md
> +Retornar valores também podem transferir a posse de um valor. Aqui está um
podem -> pode

2018-02-20 11:03 UTC, leodasvacas commented on src/ch04-02-references-and-borrowing.md
> +1. Em qualquer momento, você pode ter *um ou outro*, mas não os dois:
Qualquer momento -> um dado momento

2018-02-20 11:03 UTC, leodasvacas commented on src/ch04-03-slices.md
> +    // palavra ainda tem o valor 5, aqui, mas já não há mais uma string para a
"5, aqui" -> " 5 aqui"

2018-02-20 11:03 UTC, leodasvacas commented on src/ch04-03-slices.md
> +Os conceitos de ownership, borrowing, e slices são o que garantem a segurança de
"o que garantem" -> "os que garantem" ou "o que garante"

2018-02-20 11:09 UTC, Milack27 commented
Valeu pela revisão, @leodasvacas ! Acho válidas todas as suas colocações, vou tentar corrigir e commitar ainda hoje.

2018-02-20 12:05 UTC, Milack27 commented
@leodasvacas Sobre a palavra *ownership*, você acha melhor remover totalmente e trocar por *posse* em todas as ocorrências? Eu, particularmente, acho mais proveitoso usar *ownership* quando a gente se refere à feature, e *posse* quando a gente está explicando o que ela significa.

2018-02-20 12:08 UTC, leodasvacas commented
@Milack27 Concordo com você, usar os dois é válido até porque a tradução não está bem estabelecida ainda, acho que o uso de posse/ownership está bom como está no texto, no futuro podemos ver mais opiniões e decidir sobre isso.

2018-02-20 12:09 UTC, Milack27 commented
Show de bola!

2018-02-25 23:44 UTC, Milack27 commented
@leodasvacas Demorei um pouco mais que o prometido, haha. Foi mal!

Apliquei todas as suas sugestões, mas ainda não removi as partes em inglês. Fico no aguardo do seu aval para fazer isso.

2018-02-26 11:33 UTC, marioidival reviewed
🤔

2018-02-26 11:33 UTC, marioidival commented on src/ch04-01-what-is-ownership.md
> +> ### A Pilha e a _Heap_
Por que não traduzir _heap_?

2018-02-26 12:31 UTC, Milack27 commented on src/ch04-01-what-is-ownership.md
> +> ### A Pilha e a _Heap_
Na verdade, nem sei como se traduz isso. Acho que heap é um termo bem difundido entre os brasileiros, nunca vi ninguém usar um nome em português pra isso. Tens alguma sugestão?

2018-02-26 12:38 UTC, marioidival commented on src/ch04-01-what-is-ownership.md
> +> ### A Pilha e a _Heap_
Heap == Fila, acho que se traduziu _Stack_, deveria traduzir _Heap_ tambem ^^

2018-02-26 15:19 UTC, Milack27 commented on src/ch04-01-what-is-ownership.md
> +> ### A Pilha e a _Heap_
Eu até concordaria que deveria traduzir ou os dois ou nenhum, mas não creio que _fila_ seja uma boa tradução para heap. _Fila_ é bem usada pra se referir a uma estrutura de dados FIFO, mas nesse caso, estamos falando da região da memória onde são feitas as alocações dinâmicas.

2018-02-26 15:28 UTC, leodasvacas commented on src/ch04-01-what-is-ownership.md
> +> ### A Pilha e a _Heap_
Pilha é uma tradução bem estabelecida para stack, já heap é usado em vários contextos e nunca vi uma tradução.

2018-02-26 16:14 UTC, leodasvacas commented
Correções ok, pode remover o inglês. A questão de traduzir heap ou não pode ser decidida em uma issue separada.

2018-02-27 15:40 UTC, leodasvacas commented
Falta resolver os conflitos.

2018-02-27 16:46 UTC, merged

2018-02-27 16:46 UTC, leodasvacas commented
Mandou bem @Milack27 🎉