Tradução do capítulo 10 segunda edição 2ª versão (#16)
rust-br/rust-book-pt-br pull request #60
Opened 2018-03-02 21:30 UTC by marimeireles

2018-03-02 22:17 UTC, leoyvens reviewed
Revisão da seção `00-generics`.

2018-03-02 22:17 UTC, leoyvens commented on src/ch10-00-generics.md
> +duplicata de conceitos; em Rust, uma dessas ferramentas é a que cria tipos
duplicata -> duplicação
é a que cria -> são os

2018-03-02 22:17 UTC, leoyvens commented on src/ch10-00-generics.md
> +genéricos. Tipos genéricos são _stand-ins_ abstratos para tipos concretos ou
stand-ins -> substitutos

2018-03-02 22:17 UTC, leodasvacas commented on src/ch10-00-generics.md
> +Finalmente, nós discutiremos *tempos de vida*, que são um tipo de generalismo
generalismo -> generalização

2018-03-02 22:17 UTC, leodasvacas commented on src/ch10-00-generics.md
> +## Removendo Duplicatas por meio da Extração de uma Função
Duplicatas -> Duplicação

2018-03-02 22:17 UTC, leodasvacas commented on src/ch10-00-generics.md
> +precisarmos muda-lo.
muda-lo -> mudá-lo

2018-03-02 22:17 UTC, leodasvacas commented on src/ch10-00-generics.md
> +Para eliminar essa duplicata, nós podemos criar uma abstração, que nesse caso
duplicata -> duplicação

2018-03-02 22:17 UTC, leodasvacas commented on src/ch10-00-generics.md
> +E se nós tivéssemos duas funções, uma que acha o maior item em um corte de
como slice é um termo técnico, melhor colocar o original na primeira tradução corte (_slice_).

2018-03-14 20:01 UTC, leoyvens reviewed
Revisado `ch10-01-syntax.md`.

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +funções ou estruturas, vamos criar definições que podemos usar muitos tipos
usar muitos -> usar para muitos
tipos diferentes de -> diferentes

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +usa-lo. Declarações de tipos de nomes vão em colchetes entre o nome da função e
usa-lo -> usá-lo

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +a lista de paramêtros.
paramêtros -> parâmetros

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +trait na próxima sessão, mas de forma breve, o que esse erro está dizendo é que
sobre trait -> sobre traits
sessão -> seção

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +usar tipos que sabem como ser ordenados. A biblioteca padrão definiu que o
que o -> o

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +temos um tipo de erro de incompatibilidade.
tipo de erro de incompatibilidade -> erro de incompatibilidade de tipos

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +usar parâmetros múltiplos de tipos genéricos. Na listagem 10-8, nós mudamos a
parâmetros múltiplos -> múltiplos parâmetros

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +Em outras palavras, `Option<T>` é um enum genérico do tipo `T`. Ele têm duas
do tipo `T` -> sobre o tipo `T`

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +variantes: `Some`, que contém o valor do tipo `T`, e uma variante `None` que
o valor -> um valor

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +não contém nenhum valor. A biblioteca padrão tem que ter apenas essa deifinição
deifinição -> definição

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +Enum podem usar tipos múltiplos genéricos também. A definição do enum
tipos múltiplos genéricos também ->  múltiplos tipos genéricos também

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +`Resultado` que usamos no Capítulo 9 é um exemplo:
Não é uma boa traduzir `Result`, pois esse tipo é extremamente comum.

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +do tipo  `E`. Essa definição faz com que seja conveniente usar o enum
espaço duplo

2018-03-14 20:01 UTC, leodasvacas commented on src/ch10-01-syntax.md
> +tivéssemos duplicado cada definição particular a mão. O proccesso de
proccesso -> processo

2018-03-21 15:44 UTC, leoyvens reviewed
Revisado `ch10-02-traits.md`.

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +`Tweet`. O comportamento que precisamos cada struct possua é que seja capaz de
que precisamos cada -> que precisamos que cada

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +`Resumir` lá. Essa restrição é parte do que é chamado de a *regra do ṍrfão*,
ṍrfão -> órfão

2018-03-21 15:44 UTC, leoyvens commented on src/ch10-02-traits.md
> +qual você pode procurar se estiver interessado nesse tipo de teoria. De forma
qual -> a qual

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +padrão para o método `resumo` do trait `Resumir` ao invés de escolher de apenas
de escolher de -> de escolher

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +`Resumir` também tivesse o método `resumo_autor` qual a implementação é
qual a -> cuja

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +primordial.
primordial -> sobrecarregada

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +`T` usando o operador maior-que. Esse operador é definido com o método padrão
o método padrão -> um método padrão

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +na biblioteca padrão de trait `std::cmp::PartialOrd`. Então para que possamos
na biblioteca padrão de trait -> no trait da biblioteca padrão

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +trait  para `T` para que a função `maior` funcione em partes de qualquer tipo
partes -> cortes (você está usando esse termo para slice, certo?)

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +então eles implementam o trait `Copia`. Quando mudamos a função `maior` para
Mellhor não traduzir `Copy`.

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +função `maior` tenha domínio. Usando a função `clone` significa que
domínio -> posse
Usando -> usar

2018-03-21 15:44 UTC, leodasvacas commented on src/ch10-02-traits.md
> +`cmp_display` se seu tipo interno `T` implementa o trait `PartialOrd` que
apenas o `cmp_display` se -> o `cmp_display` apenas se

2018-03-21 15:44 UTC, leoyvens commented on src/ch10-02-traits.md
> +extesivamente utilizadas na biblioteca padrão de Rust. Por exemplo, a
extesivamente -> extensivamente

2018-04-16 19:39 UTC, leoyvens requested changes

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +## Validando Referências com Tempos de Vida
Colocar (*Lifetimes*) no primeiro uso.

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +importante: toda referência em Rust tem um *tempo de vida*, que é o escopo no qual
Aqui também vale colocar (*lifetime*).

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +inferidos, assim como a maior parte do tempo tipos são inferidos. Similarmente
a maior -> na maior

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +quando temos que anotar typos porque múltiplos tipos são possíveis, há casos em
typos -> tipo

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +genéricos de tempo de vida para que ele tenha certeza que as referênciais atuais
referênciais atuais -> referênciais reais

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +que o programa referencie dados quais nós não estamos querendo referenciar.
quais -> que

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +Quando compilarmos esse códgiso, nós teremos um erro:
códgiso -> código

2018-04-16 19:39 UTC, leoyvens commented on src/ch10-03-lifetime-syntax.md
> +Nós  queremos ser capazes de chamar essa função passando para ela dois cortes
espaço duplo depois de "Nós"

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +múltiplas referências se relacionam umas com as outras. Se tivermos uma função
umas com as outras -> uns com os outros

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +que deve corresponder suas intuições de qualquer linguage: `string1` é válida
linguage -> linguagem

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +        println!("A string mais longa é longa {}", resultado);
A string mais longa é longa -> A string mais longa é

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +`A string mais longa é longa a string longa é longa`:
A string mais longa é longa -> A string mais longa é

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +escopo interior, mas deixar a assinatura do valor para a variável `resultado`
assinatura -> atribuição

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +de vida as referências restantes deveriam ter. Nesse caso, o compilador dará um
se o Rust de forma determinista aplicar as regras mas ainda houver ambiguidade ->
se o Rust aplicar as regras de forma determinística ainda podem haver ambiguidades

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +  de escrita bem melhores.
Isso faz métodos de escrita bem melhores ->
Isso melhora a escrita de métodos

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +`primeira_palavra` na Listagem 10-27. A Assinatura começa sem nenhum tempo de
Assinatura -> assinatura

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +parâmetro tem sem próprio tempo de vida. Nós vamos chama-lo de `'a` como usual,
como usual -> como é usual

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +retorno do tempo de vida. É por isso que recebemos um erro quando tentamos
tipo de retorno do tempo de vida -> tempo de vida do tipo de retorno

2018-04-16 19:39 UTC, leodasvacas commented on src/ch10-03-lifetime-syntax.md
> +genéricos, limites de trair e tempos de vida todos em uma função!
trair -> traits

2018-04-16 19:39 UTC, leodasvacas commented
Primeira revisão completa.

2018-06-12 19:46 UTC, leodasvacas commented
@marimeireles desculpe a hiper-mega demora. Faltou alguns comentários para serem corrigidos, vc poderia solucioná-los?

2018-06-12 19:52 UTC, marimeireles commented
@leodasvacas 
Que isso, eu que demorei demais.
Claro! Não tinha visto, foi mal. Até amanhã tá pronto.

2018-08-20 14:42 UTC, leodasvacas commented
@marimeireles ping

2018-10-14 00:57 UTC, marioidival commented
@marimeireles ping

2018-10-16 11:31 UTC, marimeireles commented
Foi mal a demora, tinha feito as mudanças e esqueci de dar push! :/

2018-11-08 15:04 UTC, leodasvacas commented
@marimeireles beleza, pode tirar o inglês.

2018-11-08 15:19 UTC, marimeireles commented
>pode tirar o inglês.

Como assim?

2018-11-08 15:24 UTC, leodasvacas commented
Os parágrafos em inglês são pra facilitar a revisão, agora vc pode deixar só o texto em português.

2018-11-08 18:06 UTC, marimeireles commented
@leodasvacas , feito.

2018-11-09 14:20 UTC, leoyvens approved these changes

2018-11-09 14:21 UTC, merged

2018-11-09 14:21 UTC, leoyvens commented
@marimeireles merged, muito obrigado pela persistência! 🎉