Translate/chapter 03
rust-br/rust-book-pt-br pull request #65
Opened 2018-11-08 15:01 UTC by LorhanSohaky

Tradução de todo o capítulo 3

2018-11-09 20:02 UTC, thiagopnts requested changes
Peguei alguns typos, mas deve ser de boa corrigir agora com essa feature de suggestions do github

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-00-common-programming-concepts.md
> +> encontrará uma lista de palavras-chaves no Apêncide A.
```suggestion
> encontrará uma lista de palavras-chaves no Apêndice A.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +modo seguro e a fácil concorrência que Rust oforece. No entanto, você ainda tem
```suggestion
modo seguro e a fácil concorrência que Rust oferece. No entanto, você ainda tem
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +Esse exemplo mostra como o compilador ajuda você a encontrar error no seus programas.
```suggestion
Esse exemplo mostra como o compilador ajuda você a encontrar erros no seus programas.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +`não pode atribuir mais de uma vez à variáve
```suggestion
`não pode atribuir mais de uma vez à variável
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +esta esta situação pode ocasionar erros. Se uma parte do seu código funciona assumindo
```suggestion
esta situação pode ocasionar erros. Se uma parte do seu código funciona assumindo
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +que o valor nunca será alterdo e outra parte do seu código muda este valor, é
```suggestion
que o valor nunca será alterado e outra parte do seu código muda este valor, é
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +### Diferenças entre variáveis e contantes
```suggestion
### Diferenças entre variáveis e constantes
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +variáveis imutáveis, contantes são valores que estão vinculados ao nome e não
```suggestion
variáveis imutáveis, constantes são valores que estão vinculados ao nome e não
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +podem serem alterados, mas há algumas diferenças entre contantes e
```suggestion
podem serem alterados, mas há algumas diferenças entre constantes e
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +não se preocupe com os detalhes por agora. Apenas saiba que você precisa especificaro tipo.
```suggestion
não se preocupe com os detalhes por agora. Apenas saiba que você precisa especificar o tipo.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +Contantes podem ser declaradas em qualquer escopo, incluindo o escopo global, o que os tornam
```suggestion
Constantes podem ser declaradas em qualquer escopo, incluindo o escopo global, o que os tornam
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +A última diferença é que as contantes podem serem definidas apenas para uma expressão contante,
```suggestion
A última diferença é que as constantes podem ser definidas apenas para uma expressão constante,
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +primeira variável é * sombreada * pela segunda, o que significa que o segundo
```suggestion
primeira variável é *sombreada* pela segunda, o que significa que o segundo
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +Shadowing é diferente do que dizer que uma variável é `mut`,porque teremos um
```suggestion
Shadowing é diferente do que dizer que uma variável é `mut`, porque teremos um
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +erro em tempo de compilação se, acitentalmente, tentarmos reatribuir essa variável sem
```suggestion
erro em tempo de compilação se, acidentalmente, tentarmos reatribuir essa variável sem
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-01-variables-and-mutability.md
> +mesmo nome que a primeira, é do tipo numérico Shadowing nos poupa de
```suggestion
mesmo nome que a primeira, é do tipo numérico. Shadowing nos poupa de
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +datos estão sendo especificados para que saiba como trabalhar com esses dados. Vamos olhar para
```suggestion
dados estão sendo especificados para que saiba como trabalhar com esses dados. Vamos olhar para
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +dois subconjuntos tipos de dados: escalar e composto.
```suggestion
dois subconjuntos de tipos de dados: escalar e composto.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +Tenha em ment que Rust é uma linguagem de *tipagem estática*, o que significa
```suggestion
Tenha em mente que Rust é uma linguagem de *tipagem estática*, o que significa
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +usando `parse` na seção" Comparando o Adivinha ao Número Secreto" no
```suggestion
usando `parse` na seção "Comparando o Adivinha ao Número Secreto" no
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +inteiros, números de ponto flutuante, booleanos e caracteres. You pode reconhecer
```suggestion
inteiros, números de ponto flutuante, booleanos e caracteres. Você pode reconhecer
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +o valor associado com deve ser um inteiro sem sinal (tipos inteiros com sinal começam com `i`, em vez de `u`) que ocupa 32 bits de espaço. Tabela 3-1 mostra
```suggestion
o valor associado deve ser um inteiro sem sinal (tipos inteiros com sinal começam com `i`, em vez de `u`) que ocupa 32 bits de espaço. Tabela 3-1 mostra
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +coluna com sinal e sem sinal (por exemplo, `i16`) pode ser usada para declara um valor do tipo
```suggestion
coluna com sinal e sem sinal (por exemplo, `i16`) pode ser usada para declarar um valor do tipo
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +com ele (signed) ou se sempre for sempre
```suggestion
com ele (signed) ou se sempre for
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +quando é seguro assimit que o número é positivo, é mostrado sem sinal.
```suggestion
quando é seguro assumir que o número é positivo, é mostrado sem sinal.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +Cada variante com sinap pode armazenar números de -(2<sup>n - 1</sup>) até 2<sup>n -
```suggestion
Cada variante com sinal pode armazenar números de -(2<sup>n - 1</sup>) até 2<sup>n -
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +a -128 até 127. Variantes sem sinal pode pode armazenar números de 0 até 2<sup>n</sup> - 1,
```suggestion
a -128 até 127. Variantes sem sinal pode armazenar números de 0 até 2<sup>n</sup> - 1,
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +se sua arquitetura for 32-bit.W
```suggestion
se sua arquitetura for 32-bit.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +Esse exemplo mostra números ponto flutuantes em ação:
```suggestion
Esse exemplo mostra números de ponto flutuante em ação:
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +koreano; emoji; e caracteres não visíveis são válidos.
```suggestion
coreano; emoji; e caracteres não visíveis são válidos.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +<span class="filename">Nomr do arquivo: src/main.rs</span>
```suggestion
<span class="filename">Nome do arquivo: src/main.rs</span>
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +do valore que queremos acessar. Por exemplo:
```suggestion
do valor que queremos acessar. Por exemplo:
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +Esse programa cria uma tupla, `x`, e então cria uma uma variável para cada
```suggestion
Esse programa cria uma tupla, `x`, e então cria uma variável para cada
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +Uma outra maneira de ter uma coleção de vários valores é um *matriz*. Diferentemente
```suggestion
Uma outra maneira de ter uma coleção de vários valores é uma *matriz*. Diferentemente
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +Matrizes em Rust são diferentes de matrizes de outros linguagens, porque matrizes em Rust são de
```suggestion
Matrizes em Rust são diferentes de matrizes de outras linguagens, porque matrizes em Rust são de
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +tamanhos fixos: uma vez declado, eles não podem aumentar ou diminuir de tamanho.
```suggestion
tamanhos fixos: uma vez declarado, eles não podem aumentar ou diminuir de tamanho.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-02-data-types.md
> +formnecido pela biblioteca padrão que *é* permitido diminuir ou aumentar o tamanho.
```suggestion
fornecido pela biblioteca padrão que *é* permitido diminuir ou aumentar o tamanho.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +veriável. No snake case, todas as letras são minúsculas e sublinhado (underline) separa as palavras.
```suggestion
variável. No snake case, todas as letras são minúsculas e sublinhado (underline) separa as palavras.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +A definição de funções em Rust iniciam com `fn` e tem um par de parênteses
```suggestion
As definições de funções em Rust iniciam com `fn` e tem um par de parênteses
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +As linhas sã executadas na ordem em que aparecem na função `main`.
```suggestion
As linhas são executadas na ordem em que aparecem na função `main`.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +pode fornecer específicos para esses parâmetros. Tecnicamente, os
```suggestion
pode fornecer tipos específicos para esses parâmetros. Tecnicamente, os
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +`x` é especificado como `i32`. Quando `5` é ássadp para a `outra_funcao`, a macro
```suggestion
`x` é especificado como `i32`. Quando `5` é passado para a `outra_funcao`, a macro
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +decisão deliberada no deign do Rust: exigir anotações de tipo na definição da função,
```suggestion
decisão deliberada no design do Rust: exigir anotações de tipo na definição da função,
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +significa que o compilador quase nunca precisará que as use em outr lugar do código
```suggestion
significa que o compilador quase nunca precisará que as use em outro lugar do código
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +Este exemplo criar uma função com dois parâmetros, ambos com o
```suggestion
Este exemplo cria uma função com dois parâmetros, ambos com o 
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +Corpos de são constituídos por uma série de declarações que terminam,
```suggestion
Corpos de função são constituídos por uma série de declarações que terminam,
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +declarações e expressões e como elas afetamo os corpos
```suggestion
declarações e expressões e como elas afetam o corpo
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +Na verdade, já usamos delarações e expressões. *Declarações* são
```suggestion
Na verdade, já usamos declarações e expressões. *Declarações* são
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +Criar uma variável e atribuit um valor a ela com a palavra-chave `let` é uma declaração.
```suggestion
Criar uma variável e atribuir um valor a ela com a palavra-chave `let` é uma declaração.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +Definições não retornam valores. Assim sendo, você não pode atribuit uma declaração `let` para
```suggestion
Definições não retornam valores. Assim sendo, você não pode atribuir uma declaração `let` para
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +Expressões avaliam algo e compõem a mior parte do código que
```suggestion
Expressões avaliam algo e compõem a maior parte do código que
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +é um bloco que, nesse exemplo, avlia `4`. Esse valor fica vinculado ao `y`
```suggestion
é um bloco que, nesse exemplo, avalia `4`. Esse valor fica vinculado ao `y`
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +como parte da declaração `let`. Note que  `x + 1` sem um ponto e vírgula linhas no final.
```suggestion
como parte da declaração `let`. Note o  `x + 1` sem um ponto e vírgula no final, que é diferente da maioria das linhas vistas até agora.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +Expressões que não inclue o fim de ponyo e vírgula.
```suggestion
Expressões não terminam com ponto e vírgula.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +The value of x is: 5
```suggestion
O valor de x é: 5
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-03-how-functions-work.md
> +<span class="filename">Filename: src/main.rs</span>
```suggestion
<span class="filename">Nome do arquivo: src/main.rs</span>
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-04-comments.md
> +Em Rust, os comentários devem começar com duas barras e continuar até o final do
```suggestion
Em Rust, os comentários devem começar com duas barras e continuar até o final da
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-04-comments.md
> +// explica o que está acontecendo.
```suggestion
// explique o que está acontecendo.
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +Todas as expressões `if` começam com a palavra-chave` if`, que é seguida por uma
```suggestion
Todas as expressões `if` começam com a palavra-chave `if`, que é seguida por uma
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +discutido na seção “Comparando o Palpite ao Número Secreto” de
```suggestion
discutimos na seção “Comparando o Palpite ao Número Secreto” de
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +condição for falsa, o programa simplesmente ignorará o bloco` if` e passará para o
```suggestion
condição for falsa, o programa simplesmente ignorará o bloco `if` e passará para o
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +converter tipos não-booleanos em um booleano. Você deve explícitar e sempre fornecer
```suggestion
converter tipos não-booleanos em um booleano. Você deve explicitar e sempre fornecer
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +Todos os cinco valores de matriz aparecem no terminal, conforme esperado. Embora `indixe`
```suggestion
Todos os cinco valores de matriz aparecem no terminal, conforme esperado. Embora `indice`
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +<span class="filename">Filename: src/main.rs</span>
```suggestion
<span class="filename">Nome do arquivo: src/main.rs</span>
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +nós ainda não falamos, `rev`, para reverter o intervalo:
```suggestion
que nós ainda não falamos, `rev`, para reverter o intervalo:
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +Você conseguiu! Esse foi um capítulo considerável: você aprendeu sobre variáveis, escalar
```suggestion
Você conseguiu! Esse foi um capítulo considerável: você aprendeu sobre variáveis, tipos
```

2018-11-09 20:02 UTC, thiagopnts commented on src/ch03-05-control-flow.md
> +e tipos de dados compostos, funções, comentários, expressões `if` e loops! E se
```suggestion
de dados escalares e compostos, funções, comentários, expressões `if` e loops! E se
```

2018-11-09 20:59 UTC, LorhanSohaky commented on src/ch03-00-common-programming-concepts.md
> +> encontrará uma lista de palavras-chaves no Apêncide A.
Não entendi

2018-11-09 21:00 UTC, LorhanSohaky commented on src/ch03-01-variables-and-mutability.md
> +modo seguro e a fácil concorrência que Rust oforece. No entanto, você ainda tem
Não entendi

2018-11-09 21:04 UTC, LorhanSohaky commented on src/ch03-01-variables-and-mutability.md
> +Contantes podem ser declaradas em qualquer escopo, incluindo o escopo global, o que os tornam
Não entendi

2018-11-10 15:21 UTC, thiagopnts commented on src/ch03-00-common-programming-concepts.md
> +> encontrará uma lista de palavras-chaves no Apêncide A.
Ta escrito "Apêncide", o certo é "Apêndice", mesma coisa nos outros casos.

2018-11-10 15:34 UTC, LorhanSohaky commented on src/ch03-00-common-programming-concepts.md
> +> encontrará uma lista de palavras-chaves no Apêncide A.
Hahahaha falta de atenção minha

2018-11-12 16:01 UTC, leodasvacas commented
@thiagopnts aprovado?

2018-11-12 16:27 UTC, thiagopnts commented
@leodasvacas ainda tem várias correções pendentes, elas aparecem se clicar em `Load more` ali nas conversas, não sei se elas aparecem pra vc aceitar ou se só o @LorhanSohaky consegue aceitar

2018-11-13 00:23 UTC, LorhanSohaky commented
@thiagopnts peço desculpas pelo tanto de erros e agradeço a sua atenção à correção.

2018-11-13 13:21 UTC, thiagopnts commented
@LorhanSohaky tranquilo po, a tradução é muito longa mesmo, a gente que agradece por você ter feito :)

2018-11-14 18:12 UTC, thiagopnts approved these changes

2018-11-14 18:14 UTC, thiagopnts commented
pronto @leodasvacas!

2018-11-15 15:26 UTC, leoyvens approved these changes

2018-11-15 15:26 UTC, merged

2018-11-15 15:26 UTC, leoyvens commented
Muito obrigado @LorhanSohaky e @thiagopnts pelo trabalho em equipe!